### ISSUE TITLE
Cannot Compile On Linux

### ISSUE THREAD

**Issue by markovejnovic** [joehood/asciiplotter#1]
This library does not compile on Linux due to including `AsciiPlotter.h`. UNIX machines are case-sensitive so an import like this one fails.

**Comment by joehood** [comment]
This should be a simple fix. Thanks for pointing it out. Anything else needed for linux compatibility?

**Comment by markovejnovic** [comment]
Sorry for the late reply! That was the only issue. I moved away from this library for my own needs, but last I recall, that was all there was to it to get it to compile on *nix!
